from flask import Flask, render_template, abort, request, redirect, url_for, session,jsonify
import os
import openai
from flask_ngrok import run_with_ngrok
from pyngrok import ngrok
import re
from flask_cors import CORS

port_no = 5000
app = Flask(__name__)
CORS(app)  # Enable CORS for all routes

ngrok.set_auth_token("2PVWz3u3Iry3L3IpmZ1Owt4Sssd_sjkWd2FuyC5s5GBEm64S")
public_url =  ngrok.connect(port_no).public_url

openai.api_key = "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"

def generate_text(prompt):
    response = openai.Completion.create(
        engine="text-davinci-002",
        prompt=prompt,
        max_tokens=400,
        n=1,
        stop=None,
        temperature=0.7,
    )

    return response.choices[0].text.strip()

@app.route('/')
def hello_world():
  return '<h2>Build Story API<h2>'


@app.route('/build_story/<story>',methods=['POST', 'GET'])
def build_story(story):
    # """
    # Builds a better story by generating new ideas and plot points.
    # """
    prompt = f"Build a better story: {story}"
    suggestion = generate_text(prompt)
    
    suggestion = re.sub("\n","",suggestion)
    # suggestion = re.sub("\\u","",suggestion)
    response = suggestion

    return jsonify(response)



@app.route('/edit_text/<text>',methods=['POST', 'GET'])
def edit_text(text):

  # Define the text to be corrected

  # Define the GPT-3 prompt to correct the text
  prompt = f"Correct the following sentence: {text}"

  # Define the GPT-3 model parameters
  model_engine = "text-davinci-002"
  max_tokens = 60
  temperature = 0.5

  # Generate the corrected text using GPT-3
  response = openai.Completion.create(
      engine=model_engine,
      prompt=prompt,
      max_tokens=max_tokens,
      temperature=temperature
  )

  # Extract the corrected text from the GPT-3 response
  corrected_text = response.choices[0].text

  # Remove any extra text generated by GPT-3
  corrected_text = re.sub('Correct the following sentence: |[^\w\s]|\n', '', corrected_text)

  # Print the corrected text
  # print(corrected_text)
  return jsonify(corrected_text)


@app.route('/improve_readability/<text>',methods=['POST', 'GET'])
def improve_readability(text):
    prompt = f"Improve the following sentence: {text}"
    new_sentence = generate_text(prompt)

    new_sentence=re.sub("\n","",new_sentence)
    response = new_sentence

    return jsonify(response)

@app.route('/image/<name>',methods=['POST', 'GET'])
def Image_res(name):

    # output = request.form.to_dict()

    # name = output["name"]


    openai.api_key = "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"

    response = openai.Image.create(
        prompt=name,
        n=1,
        size="256x256",
    )

    restult = response["data"][0]["url"] 
    img_tag = f'<img src="{restult}">'
    return img_tag

print(f"To access the global link, please click {public_url}")

app.run(port=port_no)
    









# Example usage
# new_story = build_story(story)
# print(new_story)

# text = "I am writing a book about the history of the universe. It covers everything from the Big Bang to the present day."
# edited_text = edit_text(text)
# print(edited_text)

# text = "She opened the door and went inside. It was dark and she couldn't see anything. She tried to turn on the light, but the switch didn't work."
# readable_text = improve_readability(text)
# print(readable_text)

# def build_story(story):
#     """
#     Builds a better story by generating new ideas and plot points.
#     """
#     prompt = f"Build a better story: {story}"
#     suggestion = generate_text(prompt)
#     return suggestion

# def edit_text(text):
#     """
#     Edits the text to improve its quality, grammar and syntax.
#     """
#     prompt = f"Edit the following text: {text}"
#     suggestion = generate_text(prompt)
#     return suggestion

# def improve_readability(text):
#     """
#     Improves the readability of the text by restructuring sentences and making it more coherent.
#     """
#     sentences = re.split("(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?)\s", text)
#     new_sentences = []

#     for sentence in sentences:
#         prompt = f"Restructure the following sentence: {sentence}"
#         new_sentence = generate_text(prompt)
#         new_sentences.append(new_sentence)

#     new_text = " ".join(new_sentences)
#     return new_text


# app.run(port=port_no)

# # Example usage
# story = "Once upon a time, there was a princess who lived in a castle."
# new_story = build_story(story)
# print(new_story)

# text = "I am writing a book about the history of the universe. It covers everything from the Big Bang to the present day."
# edited_text = edit_text(text)
# print(edited_text)

# text = "She opened the door and went inside. It was dark and she couldn't see anything. She tried to turn on the light, but the switch didn't work."
# readable_text = improve_readability(text)
# print(readable_text)

# import openai
# import re

# # Define your OpenAI API key
# openai.api_key = "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"

# # Define the text to be corrected
# text = "I is a big fan of OpenAI"

# # Define the GPT-3 prompt to correct the text
# prompt = f"Correct the following sentence: {text}"

# # Define the GPT-3 model parameters
# model_engine = "text-davinci-002"
# max_tokens = 60
# temperature = 0.5

# # Generate the corrected text using GPT-3
# response = openai.Completion.create(
#     engine=model_engine,
#     prompt=prompt,
#     max_tokens=max_tokens,
#     temperature=temperature
# )

# # Extract the corrected text from the GPT-3 response
# corrected_text = response.choices[0].text

# # Remove any extra text generated by GPT-3
# corrected_text = re.sub('Correct the following sentence: |[^\w\s]|\n', '', corrected_text)

# # Print the corrected text
# print(corrected_text)

